/** Gemini Agent mood board — black glass, blue aurora, spectral rims */
export const PANEL_STYLES = [
    ':host{display:block;position:relative}',
    ':host(:hover) .panel,.panel.undo-active{opacity:1}',
    ':host{--ktt-idle-opacity:.24;--ktt-font:"Google Sans","Roboto",Arial,sans-serif;--ktt-radius-sm:14px;--ktt-radius-md:20px;--ktt-radius-lg:32px;--ktt-radius-pill:999px;--ktt-black:#000;--ktt-surface:rgba(0,0,0,.78);--ktt-surface-elevated:rgba(255,255,255,.06);--ktt-surface-container:rgba(255,255,255,.08);--ktt-surface-container-high:rgba(255,255,255,.12);--ktt-surface-hover:rgba(255,255,255,.14);--ktt-glass:rgba(255,255,255,.10);--ktt-on-surface:#f8fafc;--ktt-on-surface-variant:#94a3b8;--ktt-on-surface-muted:#64748b;--ktt-outline:rgba(255,255,255,.12);--ktt-outline-variant:rgba(255,255,255,.06);--ktt-primary:#38bdf8;--ktt-primary-deep:#1d4ed8;--ktt-on-primary:#fff;--ktt-primary-container:rgba(56,189,248,.16);--ktt-on-primary-container:#bae6fd;--ktt-link:#7dd3fc;--ktt-warning:#fbbf24;--ktt-warning-container:rgba(251,191,36,.12);--ktt-blur:blur(14px);--ktt-glow:0 8px 28px rgba(0,0,0,.45);--ktt-glow-hover:0 10px 36px rgba(0,0,0,.55);--ktt-focus-ring:0 0 0 2px rgba(0,0,0,.8),0 0 0 4px rgba(56,189,248,.75);--ktt-gradient-spectrum:linear-gradient(90deg,#f87171,#fbbf24,#4ade80,#38bdf8,#818cf8,#e879f9);--ktt-gradient-blue-v:linear-gradient(180deg,#7dd3fc 0%,#3b82f6 38%,#1e3a8a 72%,#000 100%);--ktt-gradient-blue-h:linear-gradient(90deg,#67e8f9 0%,#3b82f6 55%,#1d4ed8 100%);--ktt-gradient-blue-soft:linear-gradient(145deg,rgba(125,211,252,.22) 0%,rgba(59,130,246,.14) 50%,rgba(30,58,138,.08) 100%);--ktt-gradient-header:linear-gradient(180deg,rgba(125,211,252,.18) 0%,rgba(59,130,246,.08) 45%,transparent 100%);--ktt-gradient-hero:radial-gradient(ellipse 90% 80% at 50% 0%,rgba(56,189,248,.28),rgba(29,78,216,.12) 45%,transparent 70%),linear-gradient(180deg,rgba(125,211,252,.12),rgba(0,0,0,.2));--ktt-gradient-undo:linear-gradient(90deg,rgba(56,189,248,.35),rgba(129,140,248,.2),transparent);--ktt-gradient-progress:linear-gradient(90deg,#67e8f9,#38bdf8,#3b82f6,#818cf8);--ktt-gradient-text:linear-gradient(180deg,#e0f2fe 0%,#7dd3fc 40%,#3b82f6 100%);--ktt-accent-ui:#fbbf24;--ktt-accent-mixed:#4ade80;--ktt-accent-network:#38bdf8;--ktt-accent-default:#60a5fa}',
    '@media (prefers-color-scheme:light){:host{--ktt-surface:rgba(255,255,255,.88);--ktt-surface-elevated:rgba(255,255,255,.95);--ktt-surface-container:rgba(15,23,42,.05);--ktt-surface-container-high:rgba(15,23,42,.08);--ktt-surface-hover:rgba(15,23,42,.07);--ktt-glass:rgba(255,255,255,.72);--ktt-on-surface:#0f172a;--ktt-on-surface-variant:#475569;--ktt-on-surface-muted:#64748b;--ktt-outline:rgba(15,23,42,.12);--ktt-outline-variant:rgba(15,23,42,.06);--ktt-primary:#0284c7;--ktt-primary-deep:#1d4ed8;--ktt-on-primary:#fff;--ktt-primary-container:rgba(2,132,199,.10);--ktt-on-primary-container:#0369a1;--ktt-link:#0284c7;--ktt-glow:0 8px 24px rgba(15,23,42,.12);--ktt-glow-hover:0 10px 32px rgba(15,23,42,.16);--ktt-gradient-header:linear-gradient(180deg,rgba(125,211,252,.20) 0%,transparent 100%);--ktt-gradient-hero:radial-gradient(ellipse 90% 80% at 50% 0%,rgba(56,189,248,.14),transparent 65%),linear-gradient(180deg,rgba(241,245,249,.9),rgba(255,255,255,.6));--ktt-gradient-undo:linear-gradient(90deg,rgba(2,132,199,.16),transparent);--ktt-gradient-text:linear-gradient(180deg,#0369a1,#0284c7,#0ea5e9)}}',
    '@media (prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}',

    /* ── Panel: black glass + spectral rim ── */
    '.panel{position:relative;width:286px;color:var(--ktt-on-surface);background:var(--ktt-surface);backdrop-filter:var(--ktt-blur);-webkit-backdrop-filter:var(--ktt-blur);border-radius:var(--ktt-radius-lg);overflow:hidden;font:13px/1.45 var(--ktt-font);opacity:var(--ktt-idle-opacity);transition:opacity .35s cubic-bezier(.4,0,.2,1),box-shadow .35s cubic-bezier(.4,0,.2,1);box-shadow:var(--ktt-glow)}',
    '.panel::before{content:"";position:absolute;inset:0;border-radius:inherit;padding:1px;background:rgba(255,255,255,.14);-webkit-mask:linear-gradient(#fff 0 0) content-box,linear-gradient(#fff 0 0);-webkit-mask-composite:xor;mask-composite:exclude;pointer-events:none;opacity:.55}',
    '.panel::after{content:"";position:absolute;inset:1px;border-radius:calc(var(--ktt-radius-lg) - 1px);background:linear-gradient(180deg,rgba(125,211,252,.06),transparent 35%);pointer-events:none;z-index:0}',
    '.panelAura{display:none}',
    ':host(:hover) .panel{box-shadow:var(--ktt-glow-hover);opacity:1}',
    '.panel.collapsed .panelContent{display:none}',
    '.panelContent{position:relative;z-index:1}',

    /* ── Header ── */
    '.header{position:relative;display:flex;align-items:center;justify-content:space-between;gap:6px;padding:10px 12px 9px;background:var(--ktt-gradient-header),var(--ktt-glass);backdrop-filter:var(--ktt-blur);-webkit-backdrop-filter:var(--ktt-blur);user-select:none;min-height:34px;cursor:move;overflow:hidden;border-bottom:1px solid var(--ktt-outline-variant)}',
    '.header::after{content:"";position:absolute;left:10%;right:10%;top:0;height:1px;background:rgba(255,255,255,.18);opacity:.7;pointer-events:none}',
    '.headerDefault{display:flex;align-items:center;justify-content:space-between;gap:8px;min-width:0;flex:1;position:relative;z-index:1}',
    '.panel.undo-active .header{background:var(--ktt-gradient-undo),var(--ktt-primary-container);align-items:flex-start;min-height:auto;overflow:visible}',
    '@keyframes undoFlash{0%,100%{filter:brightness(1)}50%{filter:brightness(1.2)}}',
    '@keyframes orbPulse{0%,100%{opacity:.75;transform:scale(1)}50%{opacity:1;transform:scale(1.06)}}',
    '@keyframes spectrumShift{0%,100%{filter:hue-rotate(0deg)}50%{filter:hue-rotate(18deg)}}',
    '.panel.undo-fresh .header{animation:undoFlash .6s ease-in-out 4,orbPulse 2.4s ease-in-out infinite}',
    '.panel.undo-active .headerDefault{display:none}',
    '.headerDrag{display:flex;align-items:center;gap:9px;min-width:0;flex:1;cursor:move}',
    '.headerControls{display:flex;align-items:center;gap:6px;flex-shrink:0;position:relative;z-index:1}',
    '.headerBtn{width:28px;height:28px;flex-shrink:0;cursor:pointer;border-radius:var(--ktt-radius-pill);background:var(--ktt-glass);backdrop-filter:var(--ktt-blur);-webkit-backdrop-filter:var(--ktt-blur);border-color:var(--ktt-outline-variant)}',
    '.headerBtn svg{width:13px;height:13px}',
    '.brandMark{position:relative;display:inline-flex;align-items:center;justify-content:center;width:22px;height:22px;border-radius:50%;background:var(--ktt-glass);border:1px solid var(--ktt-outline-variant);color:var(--ktt-on-surface-variant);font-size:10px;font-weight:700;flex-shrink:0}',
    '.brandMark::before{display:none}',
    '.title{font-weight:800;letter-spacing:-.03em;font-size:13px;color:#fff}',
    '.versionBtn{appearance:none;border:1px solid var(--ktt-outline-variant);background:var(--ktt-glass);backdrop-filter:var(--ktt-blur);-webkit-backdrop-filter:var(--ktt-blur);color:var(--ktt-on-surface-variant);border-radius:var(--ktt-radius-pill);padding:5px 11px;font:11px var(--ktt-font);cursor:pointer;white-space:nowrap;transition:background .2s cubic-bezier(.4,0,.2,1),color .2s ease,box-shadow .2s ease}',
    '.versionBtn:hover{background:var(--ktt-surface-hover);color:#fff}',
    '.badge{font-size:9px;border-radius:var(--ktt-radius-pill);padding:4px 10px;background:var(--ktt-glass);border:1px solid var(--ktt-outline-variant);color:var(--ktt-on-surface-variant);text-transform:uppercase;font-weight:700;letter-spacing:.07em}',

    /* ── Project strip ── */
    '.projectBox{margin:0;padding:8px 12px 7px;border-bottom:1px solid var(--ktt-outline-variant);display:grid;gap:6px;background:linear-gradient(180deg,rgba(255,255,255,.04),transparent)}',
    '.projectBox.filterOn{border-bottom-color:transparent;background:linear-gradient(90deg,rgba(56,189,248,.14),transparent);box-shadow:inset 3px 0 0 var(--ktt-primary)}',
    '.projectStrip{display:grid;grid-template-columns:minmax(0,1fr);gap:6px;align-items:stretch}',
    '.projectStrip .select.field{width:100%;min-width:0;padding:6px 24px 6px 10px;font-size:10px;min-height:30px;border-radius:var(--ktt-radius-pill);font-weight:600;background:var(--ktt-glass);backdrop-filter:var(--ktt-blur);-webkit-backdrop-filter:var(--ktt-blur)}',
    '.projectActionRail{display:flex;align-items:stretch;width:100%;border-radius:var(--ktt-radius-pill);background:var(--ktt-glass);backdrop-filter:var(--ktt-blur);-webkit-backdrop-filter:var(--ktt-blur);border:1px solid var(--ktt-outline-variant);overflow:hidden;isolation:isolate}',
    '.projectActionBtn{flex:1 1 0;width:auto;min-width:28px;height:28px;border:none!important;border-radius:0!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;background:transparent!important;padding:0;color:var(--ktt-on-surface-variant);box-shadow:none!important;transition:background .22s cubic-bezier(.4,0,.2,1),color .22s ease}',
    '.projectActionBtn svg{width:13px;height:13px}',
    '.projectActionBtn:hover{background:rgba(255,255,255,.1)!important;color:#fff;box-shadow:none!important;transform:none}',
    '.projectActionBtn:active{transform:scale(.96)!important}',
    '.projectActionBtn.is-active{background:var(--ktt-gradient-blue-h)!important;color:#fff!important;box-shadow:none!important}',
    '.projectActionBtn--accent:hover{background:var(--ktt-primary-container)!important;color:var(--ktt-link)!important}',
    '.projectActionBtn--danger:hover{background:rgba(248,113,113,.14)!important;color:#fca5a5!important}',
    '.projectActionSep{width:1px;align-self:stretch;margin:5px 0;background:var(--ktt-outline-variant);flex-shrink:0}',
    '.projectSearchPanel{display:grid;gap:6px}',
    '.projectSearchPanel[hidden]{display:none}',
    '.projectSearchInputRow{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px}',
    '.projectSearchInputRow .field{padding:8px 11px;font-size:11px;min-height:34px}',
    '.projectSearchClose{width:34px;height:34px;border-radius:var(--ktt-radius-pill);border:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important}',
    '.projectSearchResults{display:grid;gap:5px;max-height:150px;overflow:auto}',
    '.projectSearchResult{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px;align-items:center;padding:9px 11px;text-align:left;background:var(--ktt-glass);backdrop-filter:var(--ktt-blur);-webkit-backdrop-filter:var(--ktt-blur);border:1px solid var(--ktt-outline-variant);border-radius:var(--ktt-radius-md);cursor:pointer;transition:background .2s ease,box-shadow .2s ease,transform .2s ease}',
    '.projectSearchResult:hover{background:rgba(56,189,248,.12);transform:translateX(2px)}',
    '.projectSearchResultName{font-size:11px;font-weight:700;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
    '.projectSearchResultMeta{color:var(--ktt-on-surface-muted);font-size:9px;white-space:nowrap}',
    '.projectSearchEmpty{padding:4px 2px;color:var(--ktt-on-surface-muted);font-size:10px}',
    '.projectEditor{display:grid;gap:8px}',
    '.projectBox.compact .projectEditor{display:none}',
    '.projectFields{display:grid;gap:6px}',
    '.projectSuggestions{display:grid;gap:6px;padding:10px;border:1px solid rgba(251,191,36,.35);border-radius:var(--ktt-radius-md);background:var(--ktt-warning-container)}',
    '.projectSuggestions[hidden]{display:none}',
    '.projectSuggestionsTitle{font-size:10px;line-height:1.35;color:var(--ktt-warning);font-weight:700}',
    '.projectSuggestionsList{display:grid;gap:5px}',
    '.projectSuggestion{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px;text-align:left;padding:8px 10px;background:var(--ktt-glass);border:1px solid var(--ktt-outline-variant);border-radius:var(--ktt-radius-sm);cursor:pointer;transition:background .15s ease}',
    '.projectSuggestion:hover{background:var(--ktt-surface-hover)}',
    '.projectSuggestion.exact{border-color:rgba(251,191,36,.5);background:var(--ktt-warning-container)}',
    '.projectSuggestionMain{min-width:0;display:grid;gap:2px}',
    '.projectSuggestionName{font-size:11px;font-weight:700;line-height:1.35;white-space:normal;overflow-wrap:anywhere;word-break:break-word}',
    '.projectSuggestionMeta{font-size:9px;color:var(--ktt-on-surface-muted);line-height:1.3;white-space:normal;overflow-wrap:anywhere;word-break:break-word}',
    '.projectSuggestionAction{font-size:9px;color:var(--ktt-link);align-self:start;padding-top:1px;font-weight:700;flex-shrink:0}',
    '.projectCreateAnyway{font-size:10px;padding:7px 10px;background:transparent;border-color:var(--ktt-outline)}',
    '.projectActionsRow{display:grid;grid-template-columns:1fr auto;gap:6px}',
    '.projectActionsRow button{font-weight:700}',
    '.projectHint{color:var(--ktt-on-surface-muted);font-size:11px;line-height:1.35}',

    /* ── Tabs: frosted segmented control ── */
    '.tabs{padding:7px 12px 0}',
    '.tabsTrack{display:grid;grid-template-columns:1fr 1fr 1fr;gap:3px;padding:3px;border-radius:var(--ktt-radius-pill);background:var(--ktt-glass);backdrop-filter:var(--ktt-blur);-webkit-backdrop-filter:var(--ktt-blur);border:1px solid var(--ktt-outline-variant);overflow:hidden;isolation:isolate}',
    '.tab{appearance:none;border:none;outline:none;background:transparent;color:var(--ktt-on-surface-variant);border-radius:var(--ktt-radius-pill);padding:6px 8px;font:11px var(--ktt-font);cursor:pointer;transition:background .25s cubic-bezier(.4,0,.2,1),color .25s ease,box-shadow .25s ease;font-weight:600;overflow:hidden;background-clip:padding-box}',
    '.tab:hover{background:rgba(255,255,255,.08);color:#fff}',
    '.tab.active{background:var(--ktt-gradient-blue-h);color:#fff}',
    '.tabPanel{display:none}',
    '.tabPanel.active{display:block}',
    '.body{padding:10px 12px 14px}',
    /* ── Summary: service chips only ── */
    '.summaryCard{position:relative;padding:9px 10px;border-radius:var(--ktt-radius-md);background:var(--ktt-gradient-hero);border:1px solid var(--ktt-outline-variant);overflow:hidden;margin-bottom:6px}',
    '.summaryCard::before{display:none}',
    '.summaryCardGlow{display:none}',
    '.summaryChips{position:relative;z-index:1;display:flex;flex-wrap:wrap;gap:5px;align-items:center}',
    '.summaryChips:empty{display:none}',
    '.serviceChip{display:inline-flex;align-items:baseline;gap:4px;padding:5px 10px;border-radius:var(--ktt-radius-pill);background:rgba(255,255,255,.07);border:1px solid var(--ktt-outline-variant);font-size:11px;line-height:1.2;white-space:nowrap}',
    '.serviceChipName{color:var(--ktt-on-surface-variant);font-weight:600;font-size:10px}',
    '.serviceChipValue{color:#fff;font-weight:800;font-size:11px}',
    '.sectionHead{display:flex;align-items:center;gap:6px;margin:2px 0 6px}',
    '.sectionHead::after{content:"";flex:1;height:1px;background:linear-gradient(90deg,rgba(56,189,248,.3),transparent)}',
    '.sectionTitle{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.12em;color:var(--ktt-on-surface-muted)}',

    /* ── Recent events: horizontal chips ── */
    '.events{display:flex;flex-direction:row;flex-wrap:nowrap;gap:6px;align-items:stretch;overflow-x:auto;overflow-y:hidden;padding:1px 2px 6px;margin:0 -2px;scroll-snap-type:x proximity;-webkit-overflow-scrolling:touch;scrollbar-width:thin;scrollbar-color:rgba(255,255,255,.18) transparent}',
    '.events::-webkit-scrollbar{height:4px}',
    '.events::-webkit-scrollbar-thumb{background:rgba(255,255,255,.18);border-radius:999px}',
    '.events::-webkit-scrollbar-track{background:transparent}',
    '.events > .empty{flex:1 0 100%;margin:0}',
    '.eventCard{display:flex;flex:0 0 auto;align-items:center;gap:7px;min-width:108px;max-width:148px;padding:5px 11px 5px 10px;border-radius:var(--ktt-radius-pill);background:var(--ktt-glass);backdrop-filter:var(--ktt-blur);-webkit-backdrop-filter:var(--ktt-blur);border:1px solid var(--ktt-outline-variant);overflow:hidden;scroll-snap-align:start;will-change:transform}',
    '.eventCard::before{content:"";width:6px;height:6px;border-radius:50%;flex-shrink:0;background:var(--ktt-primary)}',
    '.eventCard--ui::before{background:var(--ktt-accent-ui)}',
    '.eventCard--mixed::before{background:var(--ktt-accent-mixed)}',
    '.eventCard--network::before{background:var(--ktt-accent-network)}',
    '.eventBody{flex:1;min-width:0;display:grid;grid-template-columns:minmax(0,1fr) auto;grid-template-rows:auto auto;gap:0 8px;align-items:center;padding:0}',
    '.eventTop{display:flex;align-items:center;gap:6px;min-width:0;flex:1}',
    '.histSpendMain{display:contents}',
    '.histTime{font-size:10px;font-weight:700;color:var(--ktt-on-primary-container);white-space:nowrap}',
    '.eventBody .histAmount{color:#fff;font-weight:800;font-size:16px;line-height:1.1;letter-spacing:-.03em;flex-shrink:0}',
    '.histSpendService{color:var(--ktt-on-surface-variant);white-space:nowrap;font-size:10px}',
    '.source{color:var(--ktt-on-surface-muted);text-transform:uppercase;font-size:8px;letter-spacing:.06em;font-weight:700;flex-shrink:0}',
    '.eventTime{grid-column:1;grid-row:1}',
    '.eventAmount{grid-column:2;grid-row:1/span 2;align-self:center;justify-self:end}',
    '.eventService{grid-column:1;grid-row:2;min-width:0;color:var(--ktt-on-surface-variant);font-size:8px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
    '@keyframes eventChipEnter{from{opacity:0;transform:translateX(-18px) scale(.96)}to{opacity:1;transform:translateX(0) scale(1)}}',
    '.eventCard--enter{animation:eventChipEnter .34s cubic-bezier(.4,0,.2,1) both}',
    '@media (prefers-reduced-motion:reduce){.eventCard--enter{animation:none}}',

    /* ── History ── */
    '.history{display:flex;flex-direction:column;gap:6px;max-height:360px;overflow:auto;padding-right:2px}',
    '.histItem{display:flex;flex-direction:column;border-radius:var(--ktt-radius-sm);background:rgba(15,23,42,.65);border:1px solid var(--ktt-outline-variant);border-left:3px solid var(--ktt-primary);transition:transform .15s ease,border-color .15s ease;position:relative;overflow:hidden;flex:0 0 auto;min-height:44px}',
    '.histAccent{display:none!important}',
    '.histItem--ui{border-left-color:var(--ktt-accent-ui)}',
    '.histItem--mixed{border-left-color:var(--ktt-accent-mixed)}',
    '.histItem--network{border-left-color:var(--ktt-accent-network)}',
    '.histBody{padding:8px 10px;display:flex;flex-direction:column;gap:4px;min-width:0;min-height:0;flex:1 1 auto}',
    '.histHead{display:flex;align-items:center;justify-content:space-between;gap:8px}',
    '.histMain{display:flex;flex-direction:column;gap:2px;min-width:0;flex:1}',
    '.histBody .histAmount{color:#fff;font-weight:800;font-size:14px;line-height:1.2;letter-spacing:-.02em}',
    '.histSub{display:flex;flex-wrap:wrap;align-items:center;gap:6px}',
    '.histService{font-size:11px;font-weight:700;color:var(--ktt-link);white-space:nowrap}',
    '.histItem:hover{transform:translateY(-1px);border-color:rgba(56,189,248,.28)}',
    '.histDelete{width:24px;height:24px;flex-shrink:0;border:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;opacity:.5;padding:0}',
    '.histDelete:hover{opacity:1;background:rgba(255,255,255,.12)!important}',
    '.histMeta{color:var(--ktt-on-surface-variant);font-size:10px;display:flex;flex-wrap:wrap;gap:5px}',
    '.pill{border:1px solid var(--ktt-outline-variant);border-radius:var(--ktt-radius-pill);padding:2px 8px;background:rgba(255,255,255,.08);font-size:10px;font-weight:600;color:var(--ktt-on-surface-variant)}',
    '.raw{color:var(--ktt-on-surface-muted);font-size:11px;line-height:1.45;word-break:break-word}',
    '.rawLink{color:var(--ktt-link);text-decoration:none;font-weight:600}',
    '.rawLink:hover{text-decoration:underline}',
    '.histHeader{display:flex;flex-direction:column;gap:4px;font-size:10px;color:var(--ktt-on-surface-variant);min-width:0;flex:1;text-align:left}',
    '.histHeaderTop{display:flex;align-items:center;justify-content:space-between;gap:8px;min-width:0}',
    '.histHeaderLeft{display:flex;align-items:center;gap:6px;min-width:0;overflow:hidden}',
    '.histFilterBadge{flex-shrink:0;background:var(--ktt-gradient-blue-h);color:#fff;border-radius:var(--ktt-radius-pill);padding:3px 10px;font-size:10px;font-weight:800;line-height:1.35}',
    '.histHeaderSummary{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}',
    '.histHeader strong{color:#fff}',
    '.histHeaderMeta{color:var(--ktt-on-surface-muted);font-size:10px;line-height:1.3;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
    '.histAccBar{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px;align-items:center;padding:4px}',
    '.histAccToggle{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center;padding:6px 8px;border:none;border-radius:var(--ktt-radius-sm);background:transparent;color:#fff;cursor:pointer;text-align:left;min-width:0}',
    '.histAccToggle:hover{background:rgba(255,255,255,.06)}',
    '.historyAcc.open .histAccToggle{background:linear-gradient(90deg,rgba(56,189,248,.10),transparent)}',
    '.histAccFilter{display:flex;align-items:center;padding-right:4px}',
    '.histAccFilter:empty{display:none}',
    '.histAccBody{padding:0 8px 8px;gap:0}',
    '.histAccBody .history{max-height:320px;min-height:0}',
    '.historyAcc:not(.open) .histAccBody{display:none!important}',
    '.acc.historyAcc.open>.accBody.histAccBody{display:block!important}',
    '.histShowAll{flex-shrink:0;appearance:none;border:1px solid var(--ktt-outline-variant);background:var(--ktt-glass);color:var(--ktt-link);border-radius:var(--ktt-radius-pill);padding:5px 12px;font:10px/1.3 var(--ktt-font);cursor:pointer;font-weight:700;transition:background .2s ease}',
    '.histShowAll:hover{background:var(--ktt-surface-hover)}',
    '.histShowAll.active{background:var(--ktt-gradient-blue-h);border-color:transparent;color:#fff}',
    '.histItem--matched{border-color:rgba(56,189,248,.45);background:linear-gradient(135deg,rgba(56,189,248,.16),rgba(15,23,42,.62))}',

    '.grid{display:grid;grid-template-columns:1fr auto;gap:6px 12px;align-items:baseline}',
    '.label{color:var(--ktt-on-surface-variant)}',
    '.value{font-weight:700;text-align:right;color:#fff;font-size:14px}',
    '.muted{color:var(--ktt-on-surface-variant)}',

    /* ── Form controls ── */
    '.select.field{cursor:pointer;padding-right:28px}',
    '.field{width:100%;box-sizing:border-box;border:1px solid var(--ktt-outline-variant);background:var(--ktt-glass);backdrop-filter:var(--ktt-blur);-webkit-backdrop-filter:var(--ktt-blur);color:#fff;border-radius:var(--ktt-radius-sm);padding:9px 12px;font:12px var(--ktt-font);outline:none;transition:border-color .2s ease,box-shadow .2s ease}',
    '.field:focus{border-color:rgba(56,189,248,.6);box-shadow:var(--ktt-focus-ring)}',
    '.field:focus-visible{outline:none}',
    '.miniBtn{width:30px;height:30px}',
    '.miniBtn svg{width:14px;height:14px}',
    '.miniBtn.is-active{background:var(--ktt-primary-container)!important;border-color:rgba(56,189,248,.5)!important;color:var(--ktt-link)!important;box-shadow:none!important}',
    '.miniBtn.is-disabled{opacity:.35;pointer-events:none}',

    /* ── M3 Expressive checkboxes ── */
    '.m3Check{position:relative;display:inline-flex;align-items:center;gap:10px;cursor:pointer;user-select:none}',
    '.m3Check input{position:absolute;opacity:0;width:1px;height:1px;margin:-1px;padding:0;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}',
    '.m3CheckBox{position:relative;flex-shrink:0;width:20px;height:20px;border-radius:6px;border:2px solid var(--ktt-outline);background:rgba(0,0,0,.22);box-sizing:border-box;transition:border-color .22s cubic-bezier(.4,0,.2,1),background .22s ease,box-shadow .22s ease,transform .18s cubic-bezier(.4,0,.2,1)}',
    '.m3Check:hover .m3CheckBox{border-color:rgba(56,189,248,.55)}',
    '.m3Check input:focus-visible+.m3CheckBox{box-shadow:var(--ktt-focus-ring)}',
    '.m3Check input:checked+.m3CheckBox{border-color:transparent;background:var(--ktt-gradient-blue-h);transform:scale(1.04)}',
    '.m3Check input:checked+.m3CheckBox::after{content:"";position:absolute;left:6px;top:2px;width:5px;height:10px;border:solid #fff;border-width:0 2.5px 2.5px 0;transform:rotate(45deg)}',
    '.filterChip .m3CheckBox{width:16px;height:16px;border-radius:5px;border-width:1.5px}',
    '.filterChip:has(input:checked) .m3CheckBox{background:rgba(255,255,255,.22);border-color:rgba(255,255,255,.55);box-shadow:none;transform:none}',
    '.filterChip:has(input:checked) .m3CheckBox::after{left:4px;top:1px;width:4px;height:8px;border-width:0 2px 2px 0}',

    /* ── Buttons ── */
    'button{appearance:none;border:1px solid var(--ktt-outline-variant);background:var(--ktt-glass);backdrop-filter:var(--ktt-blur);-webkit-backdrop-filter:var(--ktt-blur);color:#fff;border-radius:var(--ktt-radius-pill);padding:8px 12px;font:12px var(--ktt-font);cursor:pointer;min-width:0;transition:background .2s ease,box-shadow .2s ease,transform .15s ease;font-weight:600}',
    'button:hover{background:rgba(255,255,255,.14)}',
    'button:active{transform:scale(.98)}',
    'button:focus-visible{outline:none;box-shadow:var(--ktt-focus-ring)}',
    'button.active{background:var(--ktt-gradient-blue-h);border:none}',
    '.tabsTrack .tab{border:none;backdrop-filter:none;-webkit-backdrop-filter:none;overflow:hidden;background-clip:padding-box}',
    '.tabsTrack .tab.active{border:none;backdrop-filter:none;-webkit-backdrop-filter:none;transform:none}',
    '.projectActionRail .projectActionBtn{border:none;backdrop-filter:none;-webkit-backdrop-filter:none}',
    '.histFilterBadge,.undoAction{border:none}',
    '.iconBtn{position:relative;width:36px;height:36px;display:inline-flex;align-items:center;justify-content:center;padding:0;border-radius:var(--ktt-radius-pill)}',
    '.iconBtn svg{width:17px;height:17px;stroke:currentColor;stroke-width:2;fill:none;stroke-linecap:round;stroke-linejoin:round;pointer-events:none}',
    '.iconBtn[data-tooltip]::after{content:attr(data-tooltip);position:absolute;left:50%;bottom:calc(100% + 8px);transform:translateX(-50%);padding:6px 10px;border-radius:var(--ktt-radius-sm);background:rgba(0,0,0,.9);border:1px solid var(--ktt-outline-variant);color:#fff;font-size:11px;white-space:nowrap;opacity:0;pointer-events:none;transition:opacity .12s,transform .12s;z-index:2}',
    '.iconBtn[data-tooltip]::before{content:"";position:absolute;left:50%;bottom:calc(100% + 3px);transform:translateX(-50%);border:5px solid transparent;border-top-color:rgba(0,0,0,.9);opacity:0;pointer-events:none;transition:opacity .12s;z-index:2}',
    '.iconBtn[data-tooltip]:hover::after{opacity:1;transform:translateX(-50%) translateY(-2px)}',
    '.iconBtn[data-tooltip]:hover::before{opacity:1}',
    '.empty{color:var(--ktt-on-surface-variant);font-size:12px;padding:14px 10px;text-align:center;border-radius:var(--ktt-radius-md);background:var(--ktt-glass);border:1px dashed var(--ktt-outline-variant)}',

    /* ── Settings ── */
    '.settingsForm{display:grid;gap:8px}',
    '.acc{border:1px solid var(--ktt-outline-variant);border-radius:var(--ktt-radius-md);overflow:hidden;background:var(--ktt-glass);backdrop-filter:var(--ktt-blur);-webkit-backdrop-filter:var(--ktt-blur)}',
    '.accHead{width:100%;display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:6px;align-items:center;padding:10px 12px;background:transparent;border:none;color:#fff;font:11px/1.2 var(--ktt-font);cursor:pointer;text-align:left;transition:background .2s ease}',
    '.accHead:hover{background:rgba(255,255,255,.06)}',
    '.acc.open .accHead{background:linear-gradient(90deg,rgba(56,189,248,.14),transparent)}',
    '.accTitle{font-weight:800}',
    '.accMeta{color:var(--ktt-on-surface-muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:120px}',
    '.accChevron{width:12px;height:12px;opacity:.75;transition:transform .25s cubic-bezier(.4,0,.2,1);display:inline-flex}',
    '.accChevron svg{width:12px;height:12px;stroke:currentColor}',
    '.acc.open .accChevron{transform:rotate(180deg)}',
    '.accBody{display:none;padding:10px 12px 12px;gap:7px}',
    '.acc.open .accBody{display:grid}',
    '.settingsCompactRow{display:grid;grid-template-columns:72px minmax(0,1fr);gap:4px 6px;align-items:center}',
    '.settingsLabel{color:var(--ktt-on-surface-variant);font-size:10px;font-weight:600}',
    '.settingsInline{display:flex;align-items:center;gap:6px;min-width:0}',
    '.settingsValue{color:#fff;font-weight:800;font-size:10px;min-width:28px;text-align:right}',
    '.settingsCompactRow .field{padding:5px 8px;font-size:11px;min-height:30px;border-radius:var(--ktt-radius-pill)}',
    '.settingsCompactRow input[type="range"]{padding:0;min-height:0;height:20px;accent-color:var(--ktt-primary)}',
    '.settingsCheck{display:inline-flex;align-items:center;gap:10px;color:#fff;font-size:10px;cursor:pointer;user-select:none;grid-column:1/-1;font-weight:600;padding:4px 0}',
    '.settingsStatus{color:var(--ktt-on-surface-muted);font-size:10px;line-height:1.3;word-break:break-word;grid-column:1/-1}',
    '.settingsActions{display:grid;grid-template-columns:1fr 1fr 1fr;gap:5px;grid-column:1/-1}',
    '.settingsActions--pair{grid-template-columns:1fr 1fr}',
    '.settingsActions button,.settingsReset{padding:7px 9px;font-size:10px}',
    '.settingsReset{margin-top:2px}',
    '.versionList{display:grid;gap:8px}',
    '.versionItem{display:grid;gap:3px;border-top:1px solid var(--ktt-outline-variant);padding-top:8px}',
    '.versionItem:first-child{border-top:none;padding-top:0}',
    '.versionTop{display:flex;align-items:center;justify-content:space-between;gap:8px;color:#fff;font-weight:800;font-size:11px}',
    '.versionDate{color:var(--ktt-on-surface-muted);font-weight:400}',
    '.versionChanges{margin:0;padding-left:14px;color:var(--ktt-on-surface-variant);font-size:10px;line-height:1.35}',

    /* ── Undo ── */
    '.undoToast{display:none;width:100%;grid-template-columns:auto minmax(0,1fr) auto auto;gap:6px;align-items:start;position:relative;z-index:1}',
    '.panel.undo-active .undoToast{display:grid}',
    '.undoIcon{width:28px;height:28px;display:inline-flex;align-items:center;justify-content:center;border-radius:50%;background:var(--ktt-gradient-blue-h);color:#fff;flex-shrink:0;margin-top:1px}',
    '.undoIcon svg{width:13px;height:13px;stroke:currentColor;stroke-width:2;fill:none;stroke-linecap:round;stroke-linejoin:round}',
    '.undoText{display:grid;gap:2px;min-width:0;color:var(--ktt-on-surface-variant);font-size:10px;line-height:1.25;padding-top:1px}',
    '.undoText strong{color:#fff;font-size:11px;line-height:1.3}',
    '.undoProjectButton{appearance:none;border:0;background:transparent;color:#fff;padding:0;min-width:0;max-width:100%;font:700 11px/1.35 var(--ktt-font);text-align:left;white-space:normal;overflow-wrap:anywhere;word-break:break-word;cursor:pointer}',
    '.undoProjectButton:hover{color:var(--ktt-link);text-decoration:underline}',
    '.undoMeta{color:var(--ktt-on-surface-variant);white-space:normal;overflow-wrap:anywhere;word-break:break-word}',
    '.undoAction{padding:7px 13px;font-size:11px;font-weight:800;border-radius:var(--ktt-radius-pill);background:var(--ktt-gradient-blue-h);border-color:transparent;color:#fff;flex-shrink:0;margin-top:1px}',
    '.undoClose{width:28px;height:28px;border-radius:50%;flex-shrink:0;margin-top:1px}',
    '.undoProgressTrack{display:none;position:absolute;left:0;right:0;bottom:0;height:3px;background:rgba(255,255,255,.08);overflow:hidden}',
    '.panel.undo-active .undoProgressTrack{display:block}',
    '.undoProgressBar{display:block;width:100%;height:100%;background:var(--ktt-gradient-progress);transform-origin:left center;transition:transform .1s linear}',
    '.undoProjectPicker{display:none;width:100%;position:relative;z-index:1}',
    '.panel.undo-picking .undoToast{display:none}',
    '.panel.undo-picking .undoProjectPicker{display:block}',
    '.panel.undo-picking .header{background:var(--ktt-gradient-undo),var(--ktt-primary-container)}',
    '.undoProjectChoose{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:5px;align-items:center}',
    '.undoProjectCreate{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:5px;align-items:center}',
    '.undoProjectChoose[hidden],.undoProjectCreate[hidden]{display:none}',
    '.undoProjectPicker .field{min-height:32px;padding:6px 28px 6px 10px;font-size:10px}',
    '.undoProjectSearch{grid-column:1/-1;padding-right:10px!important}',
    '.undoProjectCreate .field{grid-column:1/-1;padding-right:10px}',
    '.undoCreateProject{grid-column:1/-1;padding:8px 11px;font-size:10px;background:var(--ktt-primary-container);border-color:rgba(56,189,248,.4);color:var(--ktt-on-primary-container);font-weight:700}',
    '.undoPickerAction{padding:7px 10px;font-size:10px;font-weight:800;background:var(--ktt-gradient-blue-h);border-color:transparent;color:#fff}',
    '.undoPickerCancel{padding:7px 10px;font-size:10px}',

    '.sheetsNicknameWarn{padding:9px 14px;background:var(--ktt-warning-container);border-bottom:1px solid rgba(251,191,36,.25);color:var(--ktt-warning);font-size:10px;line-height:1.35;cursor:pointer;font-weight:600}',
    '.sheetsNicknameWarn[hidden]{display:none}',
    '.tabPanel[data-panel="settings"]{max-height:280px;overflow:auto;padding-top:4px}'
].join('');
